[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PFGIS-Tool"
authors = [{name = "Tomas", email = "thomas.carl@hotmail.com"}]
dynamic = ["version", "description"]
